# ภาษาหลัก (อังกฤษ)
en:
  locale: en-us
  # เมื่อเปิดใช้หลายภาษา เราจะย้ายเนื้อหาภาษาอังกฤษไปไว้ในโฟลเดอร์ en
  contentDir: content/en
  languageName: English

# ภาษาที่สอง (ไทย)
th:
  locale: th-th
  contentDir: content/th
  languageName: Thai
  title: "นพณธร นวชัย | ผู้เชี่ยวชาญด้านการตลาดดิจิทัล"
  params:
    description: "อาจารย์และนักวิจัยด้านการตลาดดิจิทัลและ Neuromarketing มหาวิทยาลัยหอการค้าไทย"
